apiVersion: appconnect.ibm.com/v1beta1
kind: IntegrationServer
metadata:
  name: books
spec:
  enableMetrics: true
  license:
    accept: true
    license: L-APEH-CJUCNR
    use: CloudPakForIntegrationNonProduction
  pod:
    containers:
      runtime:
        resources:
          limits:
            cpu: 300m
            memory: 350Mi
          requests:
            cpu: 300m
            memory: 300Mi
  adminServerSecure: true
  router:
    timeout: 120s
  designerFlowsOperationMode: disabled
  createDashboardUsers: true
  service:
    endpointType: http
  version: 12.0.7.0-r4
  logFormat: basic
  replicas: 1
  barURL: >-
    https://artifactory-tools.itzroks-66700099q7-0r6md0-6ccd7f378ae819553d37d5f2ee142bd6-0000.us-east.containers.appdomain.cloud:443/artifactory/generic-local/jenkins/Books_62.bar
  configurations:
    - bar-auth-config
