# This RoleBinding is just for reference.
# The actual RoleBinding is created along with the ace-tekton namespace at the infra layer.
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: custom-eci-tekton-admin
  namespace: ace-tekton
subjects:
  - kind: ServiceAccount
    name: pipeline
    namespace: ci
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin